evaluate: False
result_path: ./experiments/test
manual_seed: 1
print_freq: 20
cap_min: 50
cap_max: 2200
resume_path: ./checkpoints/SFR50_VITG_ACAR_CWtrain_ckpt_12.pth.tar

model:
    freeze_bn: True
    backbone:
        arch: slowfast50
        learnable: True
        kwargs:
            alpha: 4
            beta: 0.125
            fuse_only_conv: False
            fuse_kernel_size: 7
            slow_full_span: True

    neck:
        type: basic
        kwargs:
            bbox_jitter:
                num: 1
                scale: 0.075
            num_classes: 50
            multi_class: True
    head:
        type: acar
        kwargs:
            width: 3712 
            roi_spatial: 7
            num_classes: 50
            depth: 2

loss:
    type: ava_criterion
    kwargs:
        pose_softmax: True

train:
    root_path: frames
    annotation_path: AR_ava_format/cw_data_train1fps_woXGXJVBCQ.pkl 
    batch_size: 3

    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: [224, 224]
          - type: RandomHorizontalFlip
          - type: ToTensor
            kwargs:
                norm_value: 255.
          - type: Normalize
            kwargs:
                mean: [0.450, 0.450, 0.450]
                std: [0.225, 0.225, 0.225]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    n_epochs: 12
    val_freq: 1
    save_freq: 1

    optimizer:
        type: SGD
        kwargs:
            momentum: 0.9
            weight_decay: 0.0000001
            nesterov: True

    scheduler:
        type: step
        milestone_epochs: [5.6, 5.8]
        lr_mults: [0.1, 0.1]
        base_lr: 0.008
        warmup_lr: 0.064
        warmup_epochs: 1

val:
    root_path: frames
    annotation_path: AR_ava_format/cw_test_yolov8_on_cw_0.3.pkl    # or use ground truth:AR_ava_format/cw_data_test1fps.pkl
    batch_size: 3

    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: [224, 224]
          - type: ToTensor
            kwargs:
                norm_value: 255.
          - type: Normalize
            kwargs:
                mean: [0.450, 0.450, 0.450]
                std: [0.225, 0.225, 0.225]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    with_label: False
    eval_mAP:
        labelmap: AR_ava_format/list_action.pbtxt
        groundtruth: AR_ava_format/chaos_test_t_+1.csv
        exclusions: AR_ava_format/chaos_test_exclude.csv
